version: '3.9'
services:
  cassandra-node1: # Premier nœud (seed)
    image: cassandra:4.1
    container_name: cassandra-node1
    hostname: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: SolarMboa
      CASSANDRA_DC: Cameroun
      CASSANDRA_SEEDS: cassandra-node1
    volumes:
      - cass1-data:/var/lib/cassandra
    networks:
      - solarmboa-cassandra
    healthcheck:
      test: ["CMD", "nodetool", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      ressources:
        limits:
          memory: 521M  

  cassandra-node2: # Deuxième nœud
    image: cassandra:4.1
    container_name: cassandra-node2
    hostname: cassandra-node2
    environment:
      CASSANDRA_CLUSTER_NAME: SolarMboa
      CASSANDRA_DC: Cameroun
      CASSANDRA_SEEDS: cassandra-node1 # Pointe vers le seed
    volumes:
      - cass2-data:/var/lib/cassandra
    networks:
      - solarmboa-cassandra
    depends_on:
      cassandra-node1:
        condition: service_healthy
    deploy:
      ressources:
        limits:
          memory: 512M     

  cassandra-node3: # Troisième nœud
    image: cassandra:4.1
    container_name: cassandra-node3
    hostname: cassandra-node3
    environment:
      CASSANDRA_CLUSTER_NAME: SolarMboa
      CASSANDRA_DC: Cameroun
      CASSANDRA_SEEDS: cassandra-node1
    volumes:
      - cass3-data:/var/lib/cassandra
    networks:
      - solarmboa-cassandra
    depends_on:
      cassandra-node1:
        condition: service_healthy
    deploy:
      ressources:
        limits:
          memory: 5212M

  redis:
    image: redis
    container_name:
    restart:
    port:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-solarmboa
    deploy:
      ressources:
        limits:
          memory: 256M    



volumes:
  cass1-data: {}
  cass2-data: {}
  cass3-data: {}
  redis-data: {}
  mongo-data: {}

networks:
  solarmboa-cassandra:
    driver: bridge # Cette option est valide en version 3.9.
